version: '2.4'

services:
  minio:
    image: minio/minio
    volumes:
      - ./tmp/docker/minio/data:/export
    env_file: .env
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${ACCESS_KEY}
      MINIO_SECRET_KEY: ${SECRET_KEY}
    command: server /export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  upload-py:
    build: .
    depends_on:
      minio:
        condition: service_healthy
    volumes:
    - ./photos:/photos
